# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute complex visibility based on ABCD principle
#'
#' @param ii ABCD
#' @param kx P2VM. By default, c(0,2,2,0)
#' @param sx P2VM. By default, c(4,4,4,4)
#' @param fx Total flux in ABCD
#' 
gv_abcd2vis <- function(ii, kx = as.numeric( c(4)), sx = as.numeric( c(4)), fx = as.numeric( c(1))) {
    .Call('gRavity_gv_abcd2vis', PACKAGE = 'gRavity', ii, kx, sx, fx)
}

#' Constants of the spectrometers
#' 
#' Constants which are used in several other functions.
#' 
#' @return A named list of constants
#'
gv_const <- function() {
    .Call('gRavity_gv_const', PACKAGE = 'gRavity')
}

#' FITS file reader
#' 
#' Reads a specific image HDU or extended binary table of a FITS files.
#' This reader function is tailor made for GRAVITY FITS format but can be used
#' for generic FITS files. However, not all data types are supported.
#' 
#' Extended ASCII table and complex data types are currently not supported.
#' 
#' @param fits_name FITS file. If a vector is given, only the first is read.
#' @param hdu_name Name of the HDU to be read. Case-insensitive. If not provided, the Primary HDU is read.
#' @param col_name Name of the column of an extended HDU to be read. This is ignored if the HDU is an image.
#' 
#' @return A numeric array.
#' 
gv_readfits <- function(fits_name, hdu_name = "", col_name = "") {
    .Call('gRavity_gv_readfits', PACKAGE = 'gRavity', fits_name, hdu_name, col_name)
}

#' Strip images to relevant pixels
#' 
#' gv_sci_img2pix(img, cal$idx, cal$cnr)
#' 
gv_sci_img2pix <- function(img, idx, cnr, isYjunc = 0L, n_wd = 3L) {
    .Call('gRavity_gv_sci_img2pix', PACKAGE = 'gRavity', img, idx, cnr, isYjunc, n_wd)
}

#' Compute complex visibility of SCI fringes
#' 
#' Copied from gvspc codes.
#' 
gv_sci_pix2vis_unsorted <- function(pixels, v2pms, rdnoiz = numeric()) {
    .Call('gRavity_gv_sci_pix2vis_unsorted', PACKAGE = 'gRavity', pixels, v2pms, rdnoiz)
}

#' Solve for x in an Ax=b linear system
#'
#' The solution for x is inv(A)%*%b where inv(A) is computed by means of the
#' singular value decomposition method.
#'
gv_solvels <- function(rA, rb, rw = numeric()) {
    .Call('gRavity_gv_solvels', PACKAGE = 'gRavity', rA, rb, rw)
}

#' Compute group delay from complex visibilities
#' 
#' Copied from cppgvspc
#' 
gv_vis2gd <- function(vis) {
    .Call('gRavity_gv_vis2gd', PACKAGE = 'gRavity', vis)
}

rcpp_hello_world <- function() {
    .Call('gRavity_rcpp_hello_world', PACKAGE = 'gRavity')
}

timesTwo <- function() {
    .Call('gRavity_timesTwo', PACKAGE = 'gRavity')
}

